# Generated by Django 6.0.5 on 2026-05-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('technologie', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('Filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursus', to='promotions.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='CursusCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('obligatoire', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.cours')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursus_cours', to='promotions.cursus')),
            ],
            options={
                'ordering': ['ordre'],
                'constraints': [models.UniqueConstraint(fields=('cursus', 'ordre'), name='unique_cursus_ordre')],
                'unique_together': {('cursus', 'cours')},
            },
        ),
    ]
