# Generated by Django 6.0.5 on 2026-05-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursPlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('salle', models.CharField(max_length=100)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_planifies', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Animer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cours_planifie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.coursplanifie')),
            ],
        ),
    ]
