# Generated by Django 6.0.5 on 2026-05-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_cours_filiere_cursus_cursuscours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursus',
            old_name='Filiere',
            new_name='filiere',
        ),
    ]
