# Generated by Django 6.0.5 on 2026-05-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_coursplanifie_animer"),
        ("promotions", "0003_rename_filiere_cursus_filiere"),
    ]

    operations = []
